// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhewcJ64CF4hcS9Ermp6eJiFZmnzDeloU',
    appId: '1:18849604537:web:08e8f122470158dc12cc68',
    messagingSenderId: '18849604537',
    projectId: 'pronexus-73107',
    authDomain: 'pronexus-73107.firebaseapp.com',
    storageBucket: 'pronexus-73107.appspot.com',
    measurementId: 'G-KPKPHH00KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2aqX7DP2VBOvtv-lJWTzhf9TfBVioOlE',
    appId: '1:18849604537:android:ccd5e3b391122d5712cc68',
    messagingSenderId: '18849604537',
    projectId: 'pronexus-73107',
    storageBucket: 'pronexus-73107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg9WTgY9SW_3lUhpeDTUbAzOXg4UnqTII',
    appId: '1:18849604537:ios:63b486eaf30612e912cc68',
    messagingSenderId: '18849604537',
    projectId: 'pronexus-73107',
    storageBucket: 'pronexus-73107.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg9WTgY9SW_3lUhpeDTUbAzOXg4UnqTII',
    appId: '1:18849604537:ios:63b486eaf30612e912cc68',
    messagingSenderId: '18849604537',
    projectId: 'pronexus-73107',
    storageBucket: 'pronexus-73107.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhewcJ64CF4hcS9Ermp6eJiFZmnzDeloU',
    appId: '1:18849604537:web:8bc4e5e48b6eb59512cc68',
    messagingSenderId: '18849604537',
    projectId: 'pronexus-73107',
    authDomain: 'pronexus-73107.firebaseapp.com',
    storageBucket: 'pronexus-73107.appspot.com',
    measurementId: 'G-RDGW3NTRZJ',
  );
}
